
services:

  frontend:
    image: suss001/ict381_staycation
    ports:
      - "5000:5000"
    networks:
      - ict381network
  db:
    image: suss001/ict381_mongo
    ports:
      - "27017:27017"
    networks:
      - ict381network
  myReactApp:
    image: suss001/ict381_myreactapp
    ports:
      - "80:80"
    networks:
      - ict381network
    depends_on:
      - frontend

networks:
  ict381network:

